version: "3"

services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - jenkins
      - gitea

  jenkins:
    image: jenkins/jenkins:latest
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    ports:
      - "8080:8080"

  gitea:
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    ports:
      - "3000:3000"
    volumes:
      - ./gitea:/data
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
